name: Main Pipeline

on: ["push", "pull_request"]

defaults:
  run:
    working-directory: ./v1

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: set up go
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"

      - name: Set up gotestfmt
        uses: GoTestTools/gotestfmt-action@v2

      - name: Install gocover-cobertura
        run: go get github.com/boumenot/gocover-cobertura && go install github.com/boumenot/gocover-cobertura

      - name: check go mod
        run: go mod verify

      - name: run unit tests
        run: go test -race -json -v -coverprofile=coverage.txt ./... 2>&1 | tee /tmp/gotest.log | gotestfmt

      - name: Convert go coverage to corbetura format
        run: gocover-cobertura < coverage.txt > coverage.xml
        if: github.event_name == 'pull_request'

      - name: Generate code coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        if: github.event_name == 'pull_request'
        with:
          filename: coverage.xml
          badge: false
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "60 80"

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
