name: Main Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./v1

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go_version: ["1.20", "1.21", "1.22"]

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: set up go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}

      - name: Set up gotestfmt
        uses: GoTestTools/gotestfmt-action@v2

      - name: check go mod
        run: go mod verify

      - name: run unit tests
        run: go test -race -json -v | gotestfmt
